"""
DIYhomie — Project Materials, Tools, Product Matching & Purchase Readiness
(Build Document 55).

Turns a project's material list (hi_project_materials, generated by the planner)
into a practical materials workspace: extended purchase statuses + prices,
quantity calculations with an honest basis, substitution checks, a purchase-
readiness gate (safety items can never be silently overridden), in-store
shopping mode and receipt capture.

Collections: hi_receipts, mi_overrides, mi_substitution_checks
Shares: hi_projects, hi_project_materials, hi_measurements, hi_inventory_items, hi_analytics
LLM: gpt-4o vision (receipt OCR) + _llm_json (substitution classification).
"""
import math
import re
import uuid
from datetime import datetime, timezone
from typing import Optional, Callable, List

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

_db = None
_logger = None
_llm_json: Callable = None
_llm_key: str = ""

USER_STATUSES = ["have_it", "need_it", "need_to_rent", "need_to_borrow", "unsure",
                 "use_alternative", "ordered", "not_required"]
PURCHASE_STATUSES = ["none", "purchased", "delivered", "used", "returned", "unavailable", "substituted"]
RESOLVED_STATUSES = {"have_it", "use_alternative", "not_required"}          # counts as ready
RESOLVED_PURCHASE = {"purchased", "delivered", "used"}
SUB_CLASSES = ["safe_substitute", "verify_first", "not_recommended", "prohibited"]
CALC_BASES = ["measured", "estimated", "user_entered"]
PROHIBITED_KEYWORDS = ["gas line", "gas pipe", "flue", "breaker", "electrical panel", "pressure relief",
                       "tempered glass", "fire-rated", "fire rated", "load bearing", "load-bearing"]


def configure(db, logger, llm_json: Callable, llm_key: str):
    global _db, _logger, _llm_json, _llm_key
    _db, _logger, _llm_json, _llm_key = db, logger, llm_json, (llm_key or "")


def _now():
    return datetime.now(timezone.utc).isoformat()


def _nid():
    return str(uuid.uuid4())


async def _track(user_id, event, meta=None):
    try:
        await _db.hi_analytics.insert_one({"id": _nid(), "user_id": user_id, "event": event, "meta": meta or {}, "at": _now()})
    except Exception:
        pass


async def _project(pid: str, user_id: str) -> dict:
    p = await _db.hi_projects.find_one({"id": pid, "user_id": user_id}, {"_id": 0})
    if not p:
        raise HTTPException(status_code=404, detail="Project not found.")
    return p


async def _material(mid: str, user_id: str) -> dict:
    m = await _db.hi_project_materials.find_one({"id": mid}, {"_id": 0})
    if not m:
        raise HTTPException(status_code=404, detail="Material not found.")
    await _project(m["project_id"], user_id)
    return m


# ---------------------------------------------------------------- name matching (same approach as inventory engine)
STOP = {"the", "a", "an", "of", "for", "and", "with", "set", "pack", "kit", "inch", "in", "ft", "x"}


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9 ]", "", (s or "").lower()).strip()


def _tokens(s: str) -> set:
    return {w for w in _norm(s).split() if len(w) >= 3 and w not in STOP}


def _matches(a: str, b: str) -> bool:
    na, nb = _norm(a), _norm(b)
    if not na or not nb:
        return False
    if na in nb or nb in na:
        return True
    return bool(_tokens(a) & _tokens(b))


def _price(v) -> Optional[float]:
    try:
        f = round(float(v), 2)
        return f if f >= 0 else None
    except Exception:
        return None


def _is_resolved(m: dict) -> bool:
    return m.get("user_status") in RESOLVED_STATUSES or m.get("purchase_status") in RESOLVED_PURCHASE


# ================================================================ models
class ItemUpdateReq(BaseModel):
    user_status: Optional[str] = None
    purchase_status: Optional[str] = None
    estimated_price: Optional[float] = None
    actual_price: Optional[float] = None
    quantity: Optional[str] = None
    unit: Optional[str] = None
    notes: Optional[str] = None


class QuantityCalcReq(BaseModel):
    material_id: Optional[str] = None
    calc_type: str = "paint"          # paint | area_material | linear_material
    area_sqft: Optional[float] = None
    length_ft: Optional[float] = None
    width_ft: Optional[float] = None
    coats: int = 2
    coverage_per_unit: Optional[float] = None   # sq ft per gallon / per box / per unit
    waste_pct: float = 10.0
    unit_label: Optional[str] = None


class SubstitutionReq(BaseModel):
    required_name: str
    owned_name: str
    material_id: Optional[str] = None
    context: Optional[str] = None


class OverrideReq(BaseModel):
    check_id: str
    reason: str


class PurchasedReq(BaseModel):
    actual_price: Optional[float] = None


class ReceiptUploadReq(BaseModel):
    image_base64: str
    notes: Optional[str] = None


class ReceiptMatch(BaseModel):
    material_id: str
    price: Optional[float] = None


class ReceiptConfirmReq(BaseModel):
    merchant: Optional[str] = None
    purchase_date: Optional[str] = None
    total: Optional[float] = None
    matches: List[ReceiptMatch] = []


class ToolOwnReq(BaseModel):
    add_to_inventory: bool = True
    brand: Optional[str] = None
    storage_location: Optional[str] = None


# ================================================================ receipt OCR
async def _extract_receipt(image_base64: str) -> dict:
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage, ImageContent
        from json import loads
        chat = LlmChat(api_key=_llm_key, session_id=_nid(), system_message=(
            "You read a photographed store receipt. Return STRICT JSON: "
            "{\"merchant\": string|null, \"purchase_date\": string|null (YYYY-MM-DD if visible), "
            "\"total\": number|null, \"items\": [{\"name\": string, \"price\": number|null}], "
            "\"confidence\": one of [High, Medium, Low]}. Only include what you can actually read. "
            "If the image is unreadable return {\"confidence\": \"Low\", \"items\": []}."
        )).with_model("openai", "gpt-4o")
        out = await chat.send_message(UserMessage(text="Extract this receipt. Return only JSON.",
                                                  file_contents=[ImageContent(image_base64)]))
        s = (out or "").strip()
        if s.startswith("```"):
            s = re.sub(r"^```[a-zA-Z]*\n?|\n?```$", "", s).strip()
        data = loads(s[s.find("{"): s.rfind("}") + 1])
        return data if isinstance(data, dict) else {}
    except Exception as e:
        if _logger:
            _logger.warning(f"receipt extract failed: {e}")
        return {}


# ================================================================ substitution classification
async def _classify_substitution(required: str, owned: str, context: Optional[str], is_safety: bool) -> dict:
    combined = f"{required} {owned}".lower()
    if any(k in combined for k in PROHIBITED_KEYWORDS):
        return {"classification": "prohibited",
                "explanation": "This involves a safety-critical component. Use the exact specified product — "
                               "substitutions here are not allowed.",
                "verify_steps": []}
    data = {}
    try:
        data = await _llm_json(
            "You judge whether a DIY homeowner can substitute an item they already own for a required "
            "project item. Be conservative — when unsure, choose verify_first. Return STRICT JSON: "
            "{\"classification\": one of [safe_substitute, verify_first, not_recommended, prohibited], "
            "\"explanation\": one or two honest plain-language sentences, "
            "\"verify_steps\": [up to 3 short things to check before using it]}",
            f"Required item: {required}\nOwned item: {owned}\nProject context: {context or 'not provided'}",
            max_tokens=300, feature_area="materials")
    except Exception as e:
        if _logger:
            _logger.warning(f"substitution classify failed: {e}")
    cls = data.get("classification") if isinstance(data, dict) else None
    if cls not in SUB_CLASSES:
        cls = "verify_first"
    if is_safety and cls == "safe_substitute":
        cls = "verify_first"  # safety equipment is never auto-approved
    return {"classification": cls,
            "explanation": str(data.get("explanation") or "Verify fit, size and rating before using the owned item."),
            "verify_steps": [str(v)[:160] for v in (data.get("verify_steps") or [])][:3]}


# ================================================================ readiness
async def _readiness_payload(pid: str, user_id: str) -> dict:
    mats = await _db.hi_project_materials.find({"project_id": pid}, {"_id": 0}).to_list(300)
    meas = await _db.hi_measurements.find({"user_id": user_id, "project_id": pid},
                                          {"_id": 0, "verification_status": 1}).to_list(100)
    overrides = await _db.mi_overrides.find({"project_id": pid}, {"_id": 0}).to_list(50)
    overridden = {o["check_id"] for o in overrides}
    pending_subs = await _db.mi_substitution_checks.count_documents(
        {"project_id": pid, "classification": "verify_first", "resolved": False})

    def bucket(cat):
        return [m for m in mats if m.get("category") == cat]

    def missing_in(items):
        return [m["name"] for m in items if not _is_resolved(m)]

    mat_missing = missing_in(bucket("material"))
    tool_missing = missing_in(bucket("tool"))
    safety_missing = missing_in(bucket("safety_equipment"))
    meas_ok = (len(meas) == 0) or any(m.get("verification_status") in ("user_confirmed", "verified", "verified_future")
                                      for m in meas)

    checks = [
        {"check_id": "materials", "label": "Required materials available", "ok": not mat_missing,
         "missing": mat_missing, "safety_critical": False, "overridden": "materials" in overridden},
        {"check_id": "tools", "label": "Required tools available", "ok": not tool_missing,
         "missing": tool_missing, "safety_critical": False, "overridden": "tools" in overridden},
        {"check_id": "measurements", "label": "Measurements confirmed", "ok": meas_ok,
         "missing": [] if meas_ok else ["Confirm your captured measurements"],
         "safety_critical": False, "overridden": "measurements" in overridden},
        {"check_id": "compatibility", "label": "Product compatibility checked", "ok": pending_subs == 0,
         "missing": [] if pending_subs == 0 else [f"{pending_subs} substitution(s) still need verification"],
         "safety_critical": False, "overridden": "compatibility" in overridden},
        {"check_id": "safety_equipment", "label": "Safety equipment available", "ok": not safety_missing,
         "missing": safety_missing, "safety_critical": True, "overridden": False},
    ]
    still_needed = [n for c in checks if not c["ok"] and not c["overridden"] for n in c["missing"]]
    ready = all(c["ok"] or (c["overridden"] and not c["safety_critical"]) for c in checks)
    return {"ready": ready, "checks": checks, "still_needed": still_needed,
            "safety_blockers": safety_missing,
            "note": "Safety-critical items cannot be overridden." if safety_missing else None}


def build_router(get_current_user: Callable) -> APIRouter:
    r = APIRouter(prefix="/api/hi/materials", dependencies=[Depends(get_current_user)])

    # ------------------------------------------------------------ workspace
    @r.get("/projects/{pid}/workspace")
    async def workspace(pid: str, user: dict = Depends(get_current_user)):
        p = await _project(pid, user["id"])
        mats = await _db.hi_project_materials.find({"project_id": pid}, {"_id": 0}).sort("created_at", 1).to_list(300)
        inv = await _db.hi_inventory_items.find({"user_id": user["id"], "status": {"$ne": "archived"}},
                                                {"_id": 0, "id": 1, "name": 1, "category": 1}).to_list(500)
        receipts = await _db.hi_receipts.find({"project_id": pid}, {"_id": 0, "image_base64": 0}) \
            .sort("created_at", -1).to_list(50)

        tools, needed, owned, purchased = [], [], [], []
        for m in mats:
            m.setdefault("purchase_status", "none")
            if m.get("category") in ("tool", "safety_equipment"):
                hit = next((it for it in inv if _matches(m.get("name", ""), it.get("name", ""))), None)
                tools.append({**m, "inventory_match": hit})
            if m.get("purchase_status") in RESOLVED_PURCHASE:
                purchased.append(m)
            elif m.get("user_status") in RESOLVED_STATUSES:
                owned.append(m)
            elif m.get("purchase_status") not in ("unavailable",) and m.get("user_status") != "not_required":
                needed.append(m)

        required = [m for m in mats if m.get("category") in ("material", "tool", "safety_equipment")]
        ready_count = len([m for m in required if _is_resolved(m)])
        est = sum(_price(m.get("estimated_price")) or 0 for m in mats)
        act = sum(_price(m.get("actual_price")) or 0 for m in mats)
        await _track(user["id"], "materials_workspace_opened", {"project_id": pid})
        return {"project": {"id": p["id"], "title": p.get("title"),
                            "estimated_cost_low": p.get("estimated_cost_low"),
                            "estimated_cost_high": p.get("estimated_cost_high")},
                "ready": {"resolved": ready_count, "total": len(required)},
                "budget": {"estimated_items_total": round(est, 2), "actual_purchased_total": round(act, 2)},
                "tabs": {"needed": needed, "owned": owned, "purchased": purchased,
                         "tools": tools, "receipts": receipts},
                "statuses": USER_STATUSES, "purchase_statuses": PURCHASE_STATUSES}

    # ------------------------------------------------------------ item update (extended statuses + prices)
    @r.put("/items/{mid}")
    async def update_item(mid: str, req: ItemUpdateReq, user: dict = Depends(get_current_user)):
        await _material(mid, user["id"])
        upd = {}
        if req.user_status is not None:
            if req.user_status not in USER_STATUSES:
                raise HTTPException(status_code=400, detail="Unknown status.")
            upd["user_status"] = req.user_status
        if req.purchase_status is not None:
            if req.purchase_status not in PURCHASE_STATUSES:
                raise HTTPException(status_code=400, detail="Unknown purchase status.")
            upd["purchase_status"] = req.purchase_status
        if req.estimated_price is not None:
            upd["estimated_price"] = _price(req.estimated_price)
        if req.actual_price is not None:
            upd["actual_price"] = _price(req.actual_price)
        for f in ("quantity", "unit", "notes"):
            v = getattr(req, f)
            if v is not None:
                upd[f] = v
        if not upd:
            raise HTTPException(status_code=400, detail="Nothing to update.")
        upd["updated_at"] = _now()
        await _db.hi_project_materials.update_one({"id": mid}, {"$set": upd})
        await _track(user["id"], "material_item_updated", {"material_id": mid, "fields": list(upd.keys())})
        return await _db.hi_project_materials.find_one({"id": mid}, {"_id": 0})

    # ------------------------------------------------------------ quantity calculation with honest basis
    @r.post("/projects/{pid}/quantity-calc")
    async def quantity_calc(pid: str, req: QuantityCalcReq, user: dict = Depends(get_current_user)):
        await _project(pid, user["id"])
        # figure out area + basis
        basis = None
        area = None
        assumptions = []
        if req.area_sqft and req.area_sqft > 0:
            area, basis = float(req.area_sqft), "user_entered"
            assumptions.append(f"Area {area:g} sq ft (you entered it)")
        elif req.length_ft and req.width_ft:
            area, basis = float(req.length_ft) * float(req.width_ft), "user_entered"
            assumptions.append(f"Area {area:g} sq ft = {req.length_ft:g} × {req.width_ft:g} ft (you entered it)")
        else:
            meas = await _db.hi_measurements.find({"user_id": user["id"], "project_id": pid}, {"_id": 0}).to_list(100)
            for m in meas:
                for k in ("area_sqft", "area", "value"):
                    v = m.get(k)
                    try:
                        v = float(v)
                    except Exception:
                        continue
                    if v > 0:
                        area = v
                        basis = "measured"
                        assumptions.append(f"Area {v:g} from your saved measurement "
                                           f"“{m.get('label') or m.get('name') or 'measurement'}”")
                        break
                if area:
                    break
        if area is None:
            area, basis = 350.0, "estimated"
            assumptions.append("No measurement found — using a rough 350 sq ft estimate. Confirm before buying.")

        waste = max(0.0, min(float(req.waste_pct), 50.0))
        if req.calc_type == "paint":
            coats = max(1, min(int(req.coats), 4))
            coverage = float(req.coverage_per_unit or 350.0)
            unit = req.unit_label or "gallon"
            raw = (area * coats) / coverage
            qty = math.ceil(raw * (1 + waste / 100))
            assumptions += [f"{coats} coat(s)", f"Coverage {coverage:g} sq ft per {unit}", f"Waste allowance {waste:g}%"]
        elif req.calc_type == "area_material":
            coverage = float(req.coverage_per_unit or 20.0)
            unit = req.unit_label or "box"
            qty = math.ceil((area / coverage) * (1 + waste / 100))
            assumptions += [f"Coverage {coverage:g} sq ft per {unit}", f"Waste allowance {waste:g}%"]
        else:  # linear_material
            length = float(req.length_ft or area)
            coverage = float(req.coverage_per_unit or 8.0)
            unit = req.unit_label or "piece"
            qty = math.ceil((length / coverage) * (1 + waste / 100))
            assumptions += [f"Length {length:g} ft", f"{coverage:g} ft per {unit}", f"Waste allowance {waste:g}%"]

        result = {"recommended_quantity": qty, "unit": unit, "basis": basis,
                  "basis_label": {"measured": "Measured", "estimated": "Estimated — requires confirmation",
                                  "user_entered": "User-entered"}[basis],
                  "assumptions": assumptions,
                  "requires_confirmation": basis == "estimated"}
        if req.material_id:
            m = await _db.hi_project_materials.find_one({"id": req.material_id, "project_id": pid}, {"_id": 0, "id": 1})
            if m:
                await _db.hi_project_materials.update_one({"id": req.material_id}, {"$set": {
                    "quantity": str(qty), "unit": unit, "quantity_basis": basis,
                    "quantity_calc": result, "updated_at": _now()}})
                result["saved_to_material"] = True
        await _track(user["id"], "material_quantity_calculated", {"project_id": pid, "basis": basis})
        return result

    # ------------------------------------------------------------ substitution check
    @r.post("/projects/{pid}/substitution-check")
    async def substitution_check(pid: str, req: SubstitutionReq, user: dict = Depends(get_current_user)):
        await _project(pid, user["id"])
        if not req.required_name.strip() or not req.owned_name.strip():
            raise HTTPException(status_code=400, detail="Both the required item and your item are needed.")
        is_safety = False
        if req.material_id:
            m = await _db.hi_project_materials.find_one({"id": req.material_id}, {"_id": 0, "category": 1})
            is_safety = bool(m and m.get("category") == "safety_equipment")
        verdict = await _classify_substitution(req.required_name.strip(), req.owned_name.strip(),
                                               req.context, is_safety)
        doc = {"id": _nid(), "project_id": pid, "user_id": user["id"],
               "material_id": req.material_id, "required_name": req.required_name.strip()[:160],
               "owned_name": req.owned_name.strip()[:160], **verdict,
               "resolved": verdict["classification"] != "verify_first", "created_at": _now()}
        await _db.mi_substitution_checks.insert_one(dict(doc))
        doc.pop("_id", None)
        await _track(user["id"], "substitution_checked", {"project_id": pid, "classification": verdict["classification"]})
        return doc

    @r.post("/substitutions/{sid}/use-anyway")
    async def use_anyway(sid: str, user: dict = Depends(get_current_user)):
        sub = await _db.mi_substitution_checks.find_one({"id": sid, "user_id": user["id"]}, {"_id": 0})
        if not sub:
            raise HTTPException(status_code=404, detail="Substitution check not found.")
        if sub["classification"] == "prohibited":
            raise HTTPException(status_code=409, detail="This substitution is prohibited for safety reasons.")
        await _db.mi_substitution_checks.update_one({"id": sid}, {"$set": {"resolved": True, "used_anyway": True}})
        if sub.get("material_id"):
            await _db.hi_project_materials.update_one({"id": sub["material_id"]}, {"$set": {
                "user_status": "use_alternative", "purchase_status": "substituted",
                "notes": f"Substituted with: {sub['owned_name']}", "updated_at": _now()}})
        return {"ok": True}

    # ------------------------------------------------------------ purchase readiness
    @r.get("/projects/{pid}/purchase-readiness")
    async def purchase_readiness(pid: str, user: dict = Depends(get_current_user)):
        await _project(pid, user["id"])
        payload = await _readiness_payload(pid, user["id"])
        await _track(user["id"], "purchase_readiness_checked", {"project_id": pid, "ready": payload["ready"]})
        return payload

    @r.post("/projects/{pid}/readiness-override")
    async def readiness_override(pid: str, req: OverrideReq, user: dict = Depends(get_current_user)):
        await _project(pid, user["id"])
        if req.check_id == "safety_equipment":
            raise HTTPException(status_code=409, detail="Safety-critical items cannot be overridden.")
        if req.check_id not in ("materials", "tools", "measurements", "compatibility"):
            raise HTTPException(status_code=400, detail="Unknown readiness check.")
        if not req.reason.strip():
            raise HTTPException(status_code=400, detail="A short reason is required to continue without this.")
        await _db.mi_overrides.update_one(
            {"project_id": pid, "check_id": req.check_id},
            {"$set": {"project_id": pid, "check_id": req.check_id, "user_id": user["id"],
                      "reason": req.reason.strip()[:300], "at": _now()},
             "$setOnInsert": {"id": _nid()}}, upsert=True)
        await _track(user["id"], "readiness_overridden", {"project_id": pid, "check_id": req.check_id})
        return await _readiness_payload(pid, user["id"])

    # ------------------------------------------------------------ in-store shopping mode
    @r.get("/projects/{pid}/shopping")
    async def shopping(pid: str, user: dict = Depends(get_current_user)):
        p = await _project(pid, user["id"])
        mats = await _db.hi_project_materials.find({"project_id": pid}, {"_id": 0}).sort("created_at", 1).to_list(300)
        remaining = [m for m in mats if not _is_resolved(m) and m.get("purchase_status") != "unavailable"]
        done = [m for m in mats if m.get("purchase_status") in RESOLVED_PURCHASE]
        out = [m for m in mats if m.get("purchase_status") == "unavailable"]
        await _track(user["id"], "shopping_mode_opened", {"project_id": pid, "remaining": len(remaining)})
        return {"project": {"id": p["id"], "title": p.get("title")},
                "remaining": remaining, "purchased": done, "out_of_stock": out,
                "remaining_count": len(remaining)}

    @r.post("/items/{mid}/purchased")
    async def mark_purchased(mid: str, req: PurchasedReq, user: dict = Depends(get_current_user)):
        await _material(mid, user["id"])
        upd = {"purchase_status": "purchased", "user_status": "have_it", "updated_at": _now()}
        if req.actual_price is not None:
            upd["actual_price"] = _price(req.actual_price)
        await _db.hi_project_materials.update_one({"id": mid}, {"$set": upd})
        await _track(user["id"], "material_purchased", {"material_id": mid})
        return await _db.hi_project_materials.find_one({"id": mid}, {"_id": 0})

    @r.post("/items/{mid}/out-of-stock")
    async def out_of_stock(mid: str, user: dict = Depends(get_current_user)):
        m = await _material(mid, user["id"])
        await _db.hi_project_materials.update_one({"id": mid}, {"$set": {
            "purchase_status": "unavailable", "updated_at": _now()}})
        await _track(user["id"], "material_out_of_stock", {"material_id": mid})
        return {"ok": True, "suggestion": f"Try the substitution check to see if something else works for “{m['name']}”."}

    # ------------------------------------------------------------ receipts
    @r.post("/projects/{pid}/receipts")
    async def upload_receipt(pid: str, req: ReceiptUploadReq, user: dict = Depends(get_current_user)):
        await _project(pid, user["id"])
        if not req.image_base64:
            raise HTTPException(status_code=400, detail="A receipt photo is required.")
        extracted = await _extract_receipt(req.image_base64)
        mats = await _db.hi_project_materials.find({"project_id": pid}, {"_id": 0, "id": 1, "name": 1}).to_list(300)
        suggestions = []
        for it in (extracted.get("items") or [])[:25]:
            name = str(it.get("name") or "")
            hit = next((m for m in mats if _matches(name, m["name"])), None)
            suggestions.append({"name": name[:120], "price": _price(it.get("price")),
                                "suggested_material_id": hit["id"] if hit else None,
                                "suggested_material_name": hit["name"] if hit else None})
        doc = {"id": _nid(), "project_id": pid, "user_id": user["id"],
               "merchant": (extracted.get("merchant") or None),
               "purchase_date": (extracted.get("purchase_date") or None),
               "total": _price(extracted.get("total")),
               "confidence": extracted.get("confidence") if extracted.get("confidence") in ("High", "Medium", "Low") else "Low",
               "items": suggestions, "notes": req.notes,
               "image_base64": req.image_base64, "status": "pending_review", "created_at": _now()}
        await _db.hi_receipts.insert_one(dict(doc))
        doc.pop("_id", None)
        doc.pop("image_base64", None)
        await _track(user["id"], "receipt_uploaded", {"project_id": pid, "confidence": doc["confidence"]})
        return doc

    @r.post("/receipts/{rid}/confirm")
    async def confirm_receipt(rid: str, req: ReceiptConfirmReq, user: dict = Depends(get_current_user)):
        rc = await _db.hi_receipts.find_one({"id": rid, "user_id": user["id"]}, {"_id": 0, "image_base64": 0})
        if not rc:
            raise HTTPException(status_code=404, detail="Receipt not found.")
        upd = {"status": "confirmed", "confirmed_at": _now()}
        if req.merchant is not None:
            upd["merchant"] = req.merchant.strip()[:120] or None
        if req.purchase_date is not None:
            upd["purchase_date"] = req.purchase_date.strip()[:20] or None
        if req.total is not None:
            upd["total"] = _price(req.total)
        await _db.hi_receipts.update_one({"id": rid}, {"$set": upd})
        matched = 0
        for match in req.matches:
            m = await _db.hi_project_materials.find_one(
                {"id": match.material_id, "project_id": rc["project_id"]}, {"_id": 0, "id": 1})
            if not m:
                continue
            mupd = {"purchase_status": "purchased", "user_status": "have_it",
                    "receipt_id": rid, "updated_at": _now()}
            if match.price is not None:
                mupd["actual_price"] = _price(match.price)
            await _db.hi_project_materials.update_one({"id": match.material_id}, {"$set": mupd})
            matched += 1
        await _track(user["id"], "receipt_confirmed", {"receipt_id": rid, "matched_items": matched})
        return {"ok": True, "matched_items": matched}

    @r.get("/projects/{pid}/receipts")
    async def list_receipts(pid: str, user: dict = Depends(get_current_user)):
        await _project(pid, user["id"])
        rows = await _db.hi_receipts.find({"project_id": pid}, {"_id": 0, "image_base64": 0}) \
            .sort("created_at", -1).to_list(50)
        return {"receipts": rows}

    # ------------------------------------------------------------ project tool checklist (reusable inventory)
    @r.get("/projects/{pid}/tools")
    async def project_tools(pid: str, user: dict = Depends(get_current_user)):
        await _project(pid, user["id"])
        mats = await _db.hi_project_materials.find(
            {"project_id": pid, "category": {"$in": ["tool", "safety_equipment"]}}, {"_id": 0}).to_list(100)
        inv = await _db.hi_inventory_items.find({"user_id": user["id"], "status": {"$ne": "archived"}},
                                                {"_id": 0, "id": 1, "name": 1, "category": 1,
                                                 "brand": 1, "storage_location": 1}).to_list(500)
        rows = []
        for m in mats:
            hit = next((it for it in inv if _matches(m.get("name", ""), it.get("name", ""))), None)
            rows.append({**m, "owned": bool(hit) or m.get("user_status") == "have_it", "inventory_match": hit})
        return {"tools": rows, "owned_count": len([t for t in rows if t["owned"]]), "total": len(rows)}

    @r.post("/projects/{pid}/tools/{mid}/own")
    async def mark_tool_owned(pid: str, mid: str, req: ToolOwnReq, user: dict = Depends(get_current_user)):
        m = await _material(mid, user["id"])
        await _db.hi_project_materials.update_one({"id": mid}, {"$set": {
            "user_status": "have_it", "updated_at": _now()}})
        added = None
        if req.add_to_inventory:
            exists = await _db.hi_inventory_items.find_one(
                {"user_id": user["id"], "status": {"$ne": "archived"},
                 "name": {"$regex": f"^{re.escape(m['name'])}$", "$options": "i"}}, {"_id": 0, "id": 1})
            if not exists:
                prop = (await _db.hi_properties.find_one({"user_id": user["id"], "is_active": True}, {"_id": 0, "id": 1})
                        or await _db.hi_properties.find_one({"user_id": user["id"]}, {"_id": 0, "id": 1}))
                added = {"id": _nid(), "user_id": user["id"], "property_id": prop["id"] if prop else None,
                         "name": m["name"][:120],
                         "category": "Safety" if m.get("category") == "safety_equipment" else "Tool",
                         "brand": req.brand, "model_number": None, "quantity": None, "unit": None,
                         "storage_location": (req.storage_location or "").strip() or None,
                         "status": "have", "photo_base64": None,
                         "notes": "Added from a project tool checklist.",
                         "created_at": _now(), "updated_at": _now()}
                await _db.hi_inventory_items.insert_one(dict(added))
                added.pop("_id", None)
        await _track(user["id"], "tool_marked_owned", {"project_id": pid, "material_id": mid,
                                                       "added_to_inventory": bool(added)})
        return {"ok": True, "added_to_inventory": added}

    return r
