// Single source of truth for help/legal content + contact + social links.

export const CONTACT = {
  email: "support@diyhomie.app",
  hours: "We reply within 1 business day (Mon–Fri).",
  socials: [
    { label: "Instagram", icon: "instagram", url: "https://instagram.com/diyhomie" },
    { label: "TikTok", icon: "music-note", url: "https://tiktok.com/@diyhomie" },
    { label: "YouTube", icon: "youtube", url: "https://youtube.com/@diyhomie" },
    { label: "X", icon: "alpha-x-box-outline", url: "https://x.com/diyhomie" },
  ],
};

export const TICKET_CATEGORIES = [
  "Billing & subscription",
  "A guide was wrong",
  "App bug / crash",
  "Account / login",
  "Feature request",
  "Something else",
];

export const FAQS: { title: string; body: string }[] = [
  { title: "Is DIYhomie a real contractor?", body: "No. DIYhomie is an AI assistant that creates step-by-step informational guides. It is not a licensed contractor and does not perform work. Always use your own judgment and hire a licensed pro for anything beyond your comfort level or where required by law." },
  { title: "How are credits used?", body: "Each full guide Homie builds uses credits, and step photos are generated on demand. Your first guide is always free. Pro and Master plans include a monthly pool of credits and voice minutes." },
  { title: "Can I cancel my subscription anytime?", body: "Yes. Subscriptions are billed monthly and you can cancel anytime — you'll keep access until the end of your current billing period." },
  { title: "Why does DIYhomie ask for my location?", body: "Your location lets Homie tailor guides to your local weather (so you don't paint in the rain) and reference local building considerations. You can also just type your ZIP/city in Profile." },
  { title: "Are the guides safe to follow?", body: "Homie flags safety steps and code considerations, but it can't see your exact situation. Shut off power/water as instructed, wear protection, and stop and consult a licensed professional if anything seems unsafe or is legally required." },
  { title: "What if a guide seems wrong?", body: "Tap “Ask Homie” inside the project to troubleshoot, or submit a support ticket. We continuously improve the AI from your feedback." },
];

export const KNOWLEDGE_BASE: { category: string; articles: { title: string; body: string }[] }[] = [
  {
    category: "Getting Started",
    articles: [
      { title: "Creating your first guide", body: "From Home, type what you want to fix or build (e.g. “replace a kitchen faucet”) and tap the build button. Homie diagnoses the job, checks your tools, reviews safety, and generates step-by-step instructions with photos." },
      { title: "Adding your tools", body: "During onboarding (or in Profile) tap the kit tiers to tell Homie what you own. Guides are built around your kit and flag only what you're missing." },
    ],
  },
  {
    category: "Using a Guide",
    articles: [
      { title: "Generating step photos", body: "Open any step and tap to generate a visual. Photos are AI-rendered to match the described action so you know exactly what it should look like." },
      { title: "Troubleshooting mid-project", body: "Tap “Ask Homie” to describe what's happening (e.g. “it still wiggles”). Homie re-evaluates and gives you a focused fix." },
    ],
  },
  {
    category: "Account & Billing",
    articles: [
      { title: "Managing your plan", body: "Upgrade from the paywall or Profile. Plans are monthly and cancellable anytime; your credits refresh each billing cycle." },
      { title: "Updating your location", body: "Set your ZIP or city in Profile, or allow location access for precise, weather-aware tips." },
    ],
  },
];

export type LegalDoc = { slug: string; title: string; updated: string; sections: { heading?: string; text: string }[] };

export const LEGAL: Record<string, LegalDoc> = {
  disclaimer: {
    slug: "disclaimer",
    title: "Disclaimer",
    updated: "Updated June 2026",
    sections: [
      { heading: "Not a contractor or licensed professional", text: "DIYhomie is an AI-powered informational tool. It is NOT a licensed contractor, engineer, electrician, plumber, or other trade professional, and it does not provide professional, legal, or code-compliance advice. The guides, images, tips, and any avatar communications are generated by artificial intelligence for general informational purposes only." },
      { heading: "Use at your own risk", text: "Home improvement, repair, and maintenance work can be dangerous and may involve electricity, gas, water, heights, sharp tools, and hazardous materials. You are solely responsible for assessing your own skill level, your specific situation, and whether a task is safe and legal for you to perform. Always shut off power, gas, and water as appropriate, wear proper protective equipment, and follow manufacturer instructions." },
      { heading: "Codes & permits", text: "Building codes, permit requirements, and regulations vary by location and change over time. Homie may reference general code considerations, but you are responsible for verifying and complying with all applicable local codes and obtaining any required permits or inspections. When in doubt, hire a licensed professional." },
      { heading: "No guarantee of accuracy", text: "AI can be incomplete or incorrect. DIYhomie makes no warranty that any guide, measurement, material, cost, or instruction is accurate, complete, or suitable for your project. Verify critical information independently." },
      { heading: "Limitation of liability", text: "To the maximum extent permitted by law, DIYhomie and its creators are not liable for any injury, death, property damage, code violations, costs, or other losses arising from your use of the app or reliance on its content. If a job is beyond your ability or legally requires a licensed professional, stop and hire one." },
    ],
  },
  terms: {
    slug: "terms",
    title: "Terms of Service",
    updated: "Updated June 2026",
    sections: [
      { heading: "Acceptance", text: "By creating an account or using DIYhomie, you agree to these Terms and to our Privacy Policy and Disclaimer. If you do not agree, do not use the app." },
      { heading: "Your account", text: "You are responsible for the activity on your account and for keeping your login secure. You must be at least 18 years old (or the age of majority in your area) to subscribe." },
      { heading: "Subscriptions & billing", text: "Paid plans are billed monthly through our payment processor (Stripe). You can cancel anytime and retain access until the end of the current billing period. Credits and voice minutes refresh each cycle and do not roll over unless stated." },
      { heading: "Acceptable use", text: "Don't misuse the service, attempt to reverse engineer it, or use it for unlawful purposes. We may suspend accounts that abuse the service or our AI providers." },
      { heading: "Content", text: "AI-generated guides and images are provided for your personal use. We may improve the service using anonymized feedback. See the Disclaimer for important limitations." },
      { heading: "Changes", text: "We may update these Terms; continued use after changes means you accept them." },
    ],
  },
  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    updated: "Updated June 2026",
    sections: [
      { heading: "What we collect", text: "Account info (name, email), your survey answers (experience, tools, goals), projects you create, and optional location (ZIP/city or device GPS) used to tailor weather-aware tips." },
      { heading: "How we use it", text: "To personalize your guides, provide weather-aware advice, process subscriptions, and improve the service. We do not sell your personal information." },
      { heading: "Third parties", text: "We share limited data with service providers needed to run the app: AI providers (for generating guides/images), WeatherAPI.com (for conditions), and Stripe (for payments). They process data only to provide their service." },
      { heading: "Your choices", text: "You can update your profile, remove your location, or request account deletion by contacting support. Disabling location simply turns off weather-aware tips." },
      { heading: "Security", text: "We use industry-standard measures to protect your data, but no system is 100% secure." },
      { heading: "Contact", text: "Questions about privacy? Email support@diyhomie.app." },
    ],
  },
};

export const DISCLAIMER_SHORT =
  "DIYhomie provides AI-generated guidance only and is not a licensed contractor. Work at your own risk and follow local codes.";
